export const AppRoutes = {
  SIGNUP: "/",
  SIGNIN: "/sign-in",
  HOME: "/home",
  WEEK: "/week",
  ADD_WEEK: "/add-week",
  EDIT_WEEK: "/edit-week",
  USER_PROFILE: "/user-profile",
  EDIT_PROFILE: "/eidt-profile",
  RESET_PASSWORD: "/Reset-Password",

  // SIGNUP_ROUTE: "/signup",
  // HOMEPAGE_ROUTE: "/homepage",
  // MORNING_TEA_ROUTE: "/morningtea",
  // EVENING_TEA_ROUTE: "/eveningtea",
  // LUNCH_ROUTE: "/lunch",
  // SUMMARY_ROUTE: "/summary",
  // UPDATE_PROFILE_ROUTE: "/updateprofile",
  // SEND_CODE_ROUTE: "/sendcode",
  // VERIFY_CODE_ROUTE: "/verifycode",
  // RESET_PASSWORD_ROUTE: "/resetpassword",
};
